-- Insert the inventory items
INSERT INTO INVENTORY_ITEM ( DESIGNATION, STOCK_UNITS)
VALUES ('Seat', 50),
       ('Pedal', 60),
       ('Tube', 35),
       ('Frame', 60);

-- Insert the bundle items
INSERT INTO BUNDLE_ITEM ( DESIGNATION, ITEM_NUMBER)
VALUES ('Bike', 1),
       ('Seat', 1),
       ('Pedal', 2),
       ('Wheel', 2),
       ('Tube', 1),
       ('Frame', 1);

-- Create Node Tree for each Bundle item and define the tree schema
INSERT INTO TREE_NODE (BUNDLE_ITEM_ID) SELECT BUNDLE_ITEM_ID FROM BUNDLE_ITEM;

INSERT INTO NODE_CHILDREN (PARENT_ID, CHILD_ID) SELECT * FROM
        (SELECT TREE_NODE_ID AS PARENT_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Bike')
    CROSS JOIN
        (SELECT TREE_NODE_ID AS CHILD_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Seat') ;

INSERT INTO NODE_CHILDREN (PARENT_ID, CHILD_ID) SELECT * FROM
        (SELECT TREE_NODE_ID AS PARENT_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Bike')
    CROSS JOIN
        (SELECT TREE_NODE_ID AS CHILD_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Pedal');

INSERT INTO NODE_CHILDREN (PARENT_ID, CHILD_ID) SELECT * FROM
        (SELECT TREE_NODE_ID AS PARENT_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Bike')
    CROSS JOIN
        (SELECT TREE_NODE_ID AS CHILD_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Wheel');

INSERT INTO NODE_CHILDREN (PARENT_ID, CHILD_ID) SELECT * FROM
        (SELECT TREE_NODE_ID AS PARENT_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Wheel')
    CROSS JOIN
        (SELECT TREE_NODE_ID AS CHILD_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Frame');

INSERT INTO NODE_CHILDREN (PARENT_ID, CHILD_ID) SELECT * FROM
        (SELECT TREE_NODE_ID AS PARENT_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Wheel')
    CROSS JOIN
        (SELECT TREE_NODE_ID AS CHILD_ID FROM TREE_NODE NATURAL JOIN BUNDLE_ITEM WHERE BUNDLE_ITEM.DESIGNATION = 'Tube');

-- Insert the Bundles
INSERT INTO BUNDLE (ROOT_ID, DESIGNATION)
SELECT TREE_NODE.TREE_NODE_ID,  'Bike' AS DESIGNATION FROM TREE_NODE NATURAL JOIN  BUNDLE_ITEM  WHERE BUNDLE_ITEM.DESIGNATION = 'Bike';
